feat: add smoke-tests in ci

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -94,10 +94,41 @@ jobs:
         env:
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
           SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
+  smoke-tests:
+    needs: publish-ghcr
+    if: github.event_name == 'push'
+    runs-on: ubuntu-latest
+    steps:
+      - name: Login to GHCR
+        uses: docker/login-action@v3
+        with:
+          registry: ghcr.io
+          username: ${{ github.actor }}
+          password: ${{ secrets.GITHUB_TOKEN }}
+
+      - name: Pull and Run Published Image
+        run: |
+          IMAGE=ghcr.io/${GITHUB_REPOSITORY,,}:${{ github.sha }}
+          docker pull $IMAGE
+          docker run -d -p 3000:3000 -e NODE_ENV=production --name todo-api $IMAGE
+
+      - name: Wait for server to start
+        run: sleep 5
+
+      - name: Smoke Test 1 - Healthcheck
+        run: |
+          echo "Vérification de la route /health..."
+          HTTP_STATUS=$(curl -s -o /dev/null -w "%{http_code}" http://localhost:3000/health)
+          if [ "$HTTP_STATUS" -ne 200 ]; then
+            echo "❌ Smoke test failed! HTTP Status: $HTTP_STATUS"
+            docker logs todo-api
+            exit 1
+          fi
+          echo "✅ Healthcheck OK!"
   notify-discord:
     name: Notify Discord
     runs-on: ubuntu-latest
-    needs: [docker-build-and-test, publish-ghcr, sonarcloud-scan]
+    needs: [docker-build-and-test, publish-ghcr, sonarcloud-scan, smoke-tests]
     if: always()
 
     steps:
